// Action Types

// Sample Actions
export const SOMETHING_SUCCESSFUL = "SOMETHING_SUCCESSFUL",
             SOMETHING_FAILED = "SOMETHING_FAILED"

export const SOMETHING_RUNNING = "SOMETHING_RUNNING",
             SOMETHING_COMPLETE = "SOMETHING_COMPLETE"
